[package]
name = "iotp_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smart_house = { path = "../smart_house" }
iotp = { path = "../iotp" }
anyhow = "1.0.51"


