[package]
name = "iotp_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iotp = { path = "../iotp" }
iotp_server = { path = "../iotp_server" }